import type{PropsWithChildren}from'react';import{NavLink,useNavigate}from'react-router-dom';import{Activity,BarChart3,UserRound,Settings2,Sparkles,Sun,Moon,LogOut,ShieldCheck}from'lucide-react';import{useHealth}from'../../hooks/useHealth';import{useAuth}from'../../auth/AuthProvider';

export function Shell({children}:PropsWithChildren){
  const{isSuccess}=useHealth();
  const{user,logout,logoutAll}=useAuth();
  const navigate=useNavigate();

  const signOut=async()=>{await logout();navigate('/login');};
  const signOutAll=async()=>{await logoutAll();navigate('/login');};

  return <div className="min-h-screen"><div className="flex"><aside className="hidden min-h-screen w-64 shrink-0 border-r border-slate-200 bg-white p-5 lg:block dark:border-white/10 dark:bg-[#091925]"><div className="mb-12 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-mint"><Sparkles size={20}/></div><div><b>GRIDWISE</b><p className="text-[10px] font-bold tracking-widest text-cyan">ENERGY AI</p></div></div>{[['/',BarChart3,'Command center'],['/scenario',Settings2,'New scenario'],['/results',Sparkles,'Optimization plan'],['/profile',UserRound,'Profile']].map(([to,Icon,label])=>{const I=Icon as typeof Sparkles;return <NavLink key={to as string} to={to as string} className={({isActive})=>`mb-2 flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium ${isActive?'bg-ink text-white dark:bg-mint dark:text-ink':'muted hover:bg-slate-100 dark:hover:bg-white/5'}`}><I size={18}/>{label as string}</NavLink>})}</aside><main className="min-w-0 flex-1"><header className="flex h-20 items-center justify-between border-b border-slate-200 bg-white/80 px-5 backdrop-blur dark:border-white/10 dark:bg-[#091925]/80"><div><p className="label">Campus operations</p><b>Energy command center</b></div><div className="flex items-center gap-3"><span className={`hidden items-center gap-2 rounded-full px-3 py-1.5 text-xs font-bold sm:flex ${isSuccess?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}><Activity size={14}/>{isSuccess?'API online':'Demo mode'}</span><button onClick={()=>document.documentElement.classList.toggle('dark')} className="rounded-xl p-2 hover:bg-slate-100 dark:hover:bg-white/10"><Sun size={18} className="dark:hidden"/><Moon size={18} className="hidden dark:block"/></button><div className="text-right"><p className="text-xs font-semibold">{user?.name}</p><div className="flex items-center justify-end gap-2 text-xs text-slate-500"><button onClick={signOut} className="flex items-center gap-1 hover:text-rose-500"><LogOut size={12}/>Sign out</button>{user?.role === 'admin' && <button onClick={signOutAll} className="flex items-center gap-1 hover:text-cyan"><ShieldCheck size={12}/>All devices</button>}</div></div></div></header><div className="mx-auto max-w-[1500px] p-5 md:p-8">{children}</div></main></div></div>}

